// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yniuwnnujfribnsphxyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluaXV3bm51amZyaWJuc3BoeHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwNTQ3NzMsImV4cCI6MjA4NDYzMDc3M30.FVjbqvUfu-3aRrAvEZqqW-i9QHNpJX_S3fH1fn8Vj6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});